{
 "title": "GameVault Observabilidad",
 "tags": [
  "gamevault",
  "proyecto-3"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(gamevault_api_requests_total[1m]))",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Latencia promedio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gamevault_api_request_latency_seconds_sum[1m])) / sum(rate(gamevault_api_request_latency_seconds_count[1m]))",
     "legendFormat": "latencia promedio"
    }
   ]
  },
  {
   "title": "Gauge: videojuegos registrados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gamevault_videojuegos_total", "legendFormat": "videojuegos" }
   ]
  },
  {
   "title": "Tasa de errores HTTP (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ((sum(rate(gamevault_api_requests_total{status=~\"4..|5..\"}[5m])) or vector(0)) / clamp_min((sum(rate(gamevault_api_requests_total[5m])) or vector(0)), 0.000001))",
     "legendFormat": "errores"
    }
   ]
  },
  {
   "title": "Requests por método HTTP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rate(gamevault_api_requests_total[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Top 5 endpoints por tráfico",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (path) (rate(gamevault_api_requests_total[5m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latencia p95 / p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(gamevault_api_request_latency_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(gamevault_api_request_latency_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}